version: '3.8'

services:
  domain-app:
    build: .
    image: domain-app:latest
    container_name: domain-service
    restart: unless-stopped
    ports:
      - "8080:5000"
    volumes:
      - ./whois_cache.json:/app/whois_cache.json
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
      - FLASK_RUN_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
      - read-only:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 